### ISSUE TITLE
Totes Projekt? 

### ISSUE THREAD

**Issue by devtronic** [RubenGees/Vocabletrainer#14]
Wird die App noch aktiv weiter entwickelt? Falls nicht, unter welcher Lizenz steht die App und darf ich die App forken und ebenfalls veröffentlichen? (Natürlich mit Namensnennung)

**Comment by rubengees** [comment]
Aktuell wird die App nicht weiterentwickelt, nein. Die App hat keine Lizenz, das heißt dass folgendes gilt: https://choosealicense.com/no-permission/
Die App darf gerne geforkt, und an ihr für eigene Zwecke gearbeitet werden, ich würde aber darum bitten die App nicht erneut zu veröffentlichen, insofern größere Teile noch ähnlich sind.

**Comment by devtronic** [comment]
Alles klar, danke für die Info.
